Rails.application.routes.draw do
  resources :v_dblink_conexions
  resources :users
  resources :tipos
  resources :temporals
  resources :temp9s
  resources :temp8s
  resources :temp7s
  resources :temp6s
  resources :temp5s
  resources :temp4s
  resources :temp3s
  resources :temp21s
  resources :temp20s
  resources :temp2s
  resources :temp19s
  resources :temp18s
  resources :temp17s
  resources :temp16s
  resources :temp15s
  resources :temp14s
  resources :temp13s
  resources :temp12s
  resources :temp11s
  resources :temp10s
  resources :temp1s
  resources :temps
  resources :subpros
  resources :solnota
  resources :solicituds
  resources :smpnota
  resources :rols
  resources :requisicions
  resources :reqnota
  resources :reportes
  resources :reordens
  resources :renglons
  resources :proyectos
  resources :provs
  resources :propuesta
  resources :programas
  resources :procesos
  resources :proceso_ped_reqs
  resources :poas_asignas
  resources :poas
  resources :peds
  resources :pedidos
  resources :partidas
  resources :pacnota
  resources :pacientes
  resources :paciente_ids
  resources :nacidos
  resources :municipios
  resources :movimientos
  resources :mail_nota
  resources :mail_datos
  resources :lotes
  resources :fuentes
  resources :fianzas
  resources :evolucions
  resources :estados
  resources :entidads
  resources :domicilios
  resources :detpeds
  resources :contabilidads
  resources :clues
  resources :catalogos
  resources :cat_cabms
  resources :cat_basicos
  resources :atencions
  resources :articulos
  resources :areas
  resources :almacens
  resources :ajustes
  resources :afiliacions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
